
.PHONY: all

INSTALL_DIR=/usr/local/bin

all: install
install:
	install -m 755 ./doomemacs $(INSTALL_DIR)/doomemacs
	install -m 755 ./layoutmenu $(INSTALL_DIR)/layoutmenu
	install -m 755 ./pmenu $(INSTALL_DIR)/pmenu
	install -m 755 ./ras $(INSTALL_DIR)/ras
	install -m 755 ./tsurf $(INSTALL_DIR)/tsurf
