#!/bin/bash

DMENU='dmenu -x 0 -y 0 -z 1920 -fn dina:size=9 -nb #222222 -nf #bbbbbb -sb #af2626 -sf #eeeeee -i -l 5'
choice=$(echo -e "NetHack\nRoot terminal\nPower off\nLog-out\nExit menu" | $DMENU)

case "$choice" in
	NetHack) st -e ssh nethack@alt.org ;;
	Root\ terminal) st -e su - ;;
	Power\ off) st -i -g "50x5-900+50" -t "Power off" -e sudo poweroff ;;
	Log-out) pkill dwm ;;
	Exit-menu) exit 0 ;;
esac
