#!/bin/bash

###########################
#        SETTINGS         #
###########################
# Resolution              #
change_res=false          # If true, will change the resolution using xrandr
target_res=1920x1080      # 
###########################

# Resolution
if [[ $change_res == true ]]; then
	xrandr --size $target_res
fi

# Background
feh --bg-scale --no-fehbg ~/.wallpaper.png

# Statusbar loop
bash ~/.my-scripts/dwmbar 2>/dev/null

