#!/bin/bash

# tabbed: close tabbed when we exit the program and pass tabbed's window id as 2nd arg for surf
# surf: Use the 2nd arg as window id, enable developer tools and open the tsurf args as website
tabbed -c -r 2 surf -e '' -N "$@"
