#!/usr/bin/env bash

#===============================================================================
# Move this file to '~/.bash_profile'.
# See https://github.com/8dcc/linux-dotfiles
#===============================================================================

# Guix stuff

if [ -e "$HOME/.guix-profile" ]; then
    # Load Guix profile
    GUIX_PROFILE="$HOME/.guix-profile"
    . "$GUIX_PROFILE/etc/profile"
fi
if [ -e "$HOME/.config/guix/current" ]; then
    # Add another Guix profile for the actual `guix' command
    GUIX_PROFILE="$HOME/.config/guix/current"
    . "$GUIX_PROFILE/etc/profile"
fi
if [ -e "$HOME/.profile" ]; then
    # Written by `guix home reconfigure FILE.scm'
    . "$HOME/.profile"
fi

#-------------------------------------------------------------------------------

# Add user scripts to path, if any.
if [ -d "$HOME/.my-scripts/util" ]; then
    export PATH="$HOME/.my-scripts/util:$PATH"
fi

# Load '.bashrc' once.
if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi

# Start Xorg server, see '.xinitrc'.
startx
