#!/bin/bash

#-------- SETTINGS --------
execute=false
#--------------------------

if [[ -f $1 ]]; then
    filename="$(echo $1 | cut -d '.' -f 1).out"
    if [[ -f $filename ]]; then
        rm $filename
    fi

    gcc -o $filename $1

    if [[ $execute == true ]]; then
        if [[ -f $filename ]]; then
            echo "[gcco] Done. Running..."
            ./$filename
        else
            echo "[gcco] Error. Aborted."
        fi
    else
        echo "[gcco] Done. Compiled as $filename"
    fi
else
    echo "[gcco] Error. No such file."
fi
