#!/bin/bash

#-------- SETTINGS --------
EXECUTE=false
#--------------------------

if [[ -f $1 ]]; then
    out_file="$(echo $1 | cut -d '.' -f 1).out"

    if [[ -f $out_file ]]; then
        rm $out_file
    fi

    gcc -o $out_file $1

    if [[ $EXECUTE == true ]]; then
        if [[ -f $out_file ]]; then
            echo "[gcco] Done. Running..."
            ./$filename
        else
            echo "[gcco] Error. Can't find the binary when trying to run."
            exit 1;
        fi
    else
        echo "[gcco] Done. Compiled as $out_file"
    fi
else
    echo "[gcco] Error. No such file."      # Could not find user input
    exit 1;
fi
