#+TITLE: GNU/Linux dotfiles
#+AUTHOR: 8dcc
#+OPTIONS: toc:2
#+STARTUP: nofold

*My dotfiles, configuration files and custom builds for GNU/Linux.*

* Description

This repository contains my configuration files and app builds for my usual
GNU/Linux installations.

The [[file:apps][apps]] directory contains custom forks and configured builds for the apps I
use (most of them from [[https://suckless.org/][sucless.org]]).

The [[file:dotfiles][dotfiles]] directory contains configuration files for various files, including
my =.bashrc=, =.gdbinit=, =.clang-format=, etc.

The [[file:fonts][fonts]] directory contains some fonts that usually have to be installed
manually.

The [[file:scripts][scripts]] directory contains simple shell scripts for running various commands
or automating simple tasks.

* Keys

All the keys and shortcuts can be found in [[file:dwm-cheatsheet.org][dwm-cheatsheet.org]].

* Installation

For installing in arch, check [[file:arch-installation.org][arch-installation.org]].

* Screenshots

#+begin_quote
*Note:* Some screenshots might be a bit outdated.
#+end_quote

[[https://github.com/8dcc/linux-dotfiles/assets/29655971/ee9fccef-41ac-4e7e-ade5-824bb00a2243]]
[[https://github.com/8dcc/linux-dotfiles/assets/29655971/4f215165-f0c9-4d11-b38f-69cc1047ab0c]]
[[https://github.com/8dcc/linux-dotfiles/assets/29655971/3ede1a3c-de24-487e-a76b-5c791df10c51]]
[[https://github.com/8dcc/linux-dotfiles/assets/29655971/36214100-be13-41fb-b380-95db3e437e94]]
