#!/usr/bin/env bash
set -e

# Browser user agent, to appear more human.
USER_AGENT="Mozilla/5.0 (X11; Linux i686; rv:126.0) Gecko/20100101 Firefox/126.0"

# Max. quota for downloading multiple files. Note that the quota is checked only
# at the end of each downloaded file, so it will never result in a partially
# downloaded file.
QUOTA="500m"

# Extra options for `wget'.
WGET_OPTS="--mirror --no-parent --convert-links --wait=1 --random-wait --execute robots=off"

#-------------------------------------------------------------------------------

if [ $# -lt 1 ]; then
    echo "Usage: $(basename "$0") [OPTION...] \"URL\"" 1>&2
    exit 1
fi

if [ ! $(command -v wget) ]; then
    echo "The 'wget' command is not installed." 1>&2
    exit 1
fi

#-------------------------------------------------------------------------------

# The last command-line argument is the URL, the previous ones are the extra
# options for 'wget'.
extra_wget_opts="${@:1:$#-1}"
url="${@:$#}"

echo "URL.......: $url"
echo "User-Agent: $USER_AGENT"
echo "Max. quota: $QUOTA"
echo "Extra opts: $WGET_OPTS $extra_wget_opts"
read -p "Press any key to continue..."

wget $WGET_OPTS --quota "$QUOTA" --user-agent="$USER_AGENT" $extra_wget_opts "$url"
