#!/bin/bash
set -e

HEXDUMP=xxd
HEXDUMPFLAGS=
DIFF=diff
DIFFFLAGS='--color=auto'

if [ $# -ne 2 ]; then
    echo "Usage: $0 BIN1 BIN2" 1>&2
    exit 1
fi

if [ ! $(command -v $HEXDUMP) ]; then
    echo "The '$HEXDUMP' command is not installed." 1>&2
    exit 1
fi

if [ ! $(command -v $DIFF) ]; then
    echo "The '$DIFF' command is not installed." 1>&2
    exit 1
fi

$DIFF $DIFFFLAGS <($HEXDUMP $HEXDUMPFLAGS "$1") <($HEXDUMP $HEXDUMPFLAGS "$2")
