#!/usr/bin/env bash

# Simple script for running `emacs' through the Tor network, using `torsocks'.
# See: https://gitlab.torproject.org/tpo/core/torsocks/

TORSOCKS=torsocks
EMACS=emacs

#-------------------------------------------------------------------------------

assert_cmd() {
    if [ ! $(command -v "$1") ]; then
        echo "The '$1' command is not installed." 1>&2
        exit 1
    fi
}

assert_cmd "$TORSOCKS"
assert_cmd "$EMACS"

#-------------------------------------------------------------------------------

$TORSOCKS $EMACS "$@"
