#!/usr/bin/env bash
set -e

if [ $# -lt 2 ]; then
    echo "Usage: $(basename "$0") PATH NAME [OPTION]..." 1>&2
    exit 1
fi

if [ ! $(command -v "find") ]; then
    echo "The 'find' command is not installed." 1>&2
    exit 1
fi

find "$1" -iname "*${2}*" ${@:3}
