#!/bin/bash
set -e

# Usage:
#
#     git-log-short [OPTION]... [REVISION_RANGE] [[--] PATH...]
#
# This script does something pretty similar to:
#
#     git log --pretty=oneline
#
# Desired format:
#
#     <commit> <date> <author> <subject>
#
# Example:
#
#     * 6bd6ce1 2024-06-08 8dcc Add yt-dlp alias
#     * 6c89169 2024-05-28 8dcc Add history to gdbinit, add xxd
#     *   4b6e4c7 2024-05-22 8dcc Merge branch 'main'
#     |\
#     * | db9eab8 2024-05-22 8dcc Fix remote change detection in PS1 with [...]
#     * | 7bf74a4 2024-05-22 8dcc s/opcode bytes/instruction bytes
#     | * e0ab3b0 2024-05-21 8dcc Add USE flags for LaTeX
#     |/
#     * 0f556d3 2024-04-30 8dcc Add Iosevka 8dcc font
#
# See:
# - https://git-scm.com/docs/git-log#_pretty_formats
# - https://stackoverflow.com/q/1441010/11715554

FLAGS="--graph --date-order --date=short"
FMT="%C(yellow)%h %C(cyan)%cd %C(magenta)%aN%C(auto)%d %Creset%s"

git log $FLAGS --pretty="$FMT" $@
