#!/usr/bin/env bash
set -e

# From the `mailutils' package.
MOVEMAIL="movemail"

# Flags for `movemail'.
MOVEMAILFLAGS="--preserve --verbose"

# Custom file where the inbox URIs are stored. Each line will be used for the
# `inbox-url' argument of `movemail', and usually haves the following format:
#
#   pops://user:pass@pop.example.net
#
# More specifically:
#
#   [protocol]://[user[:pass]@]hostname[:port]
#
# See also: https://mailutils.org/wiki/Fetching_Mail_with_Movemail
CREDFILE="$HOME/Mail/credentials.gpg"

# Destination file for the incoming mail. Used for the `destfile' argument of
# `movemail'.
DESTFILE="/var/mail/$USER"

#-------------------------------------------------------------------------------

if [ ! $(command -v "$MOVEMAIL") ]; then
    echo "The '$MOVEMAIL' command is not installed." 1>&2
    exit 1
fi

#-------------------------------------------------------------------------------

# If the file is encrypted (as it should be), decrypt it.
if [[ $CREDFILE == *.gpg ]]; then
    mapfile -t contents < <(gpg --output "-" --decrypt "$CREDFILE" 2>/dev/null)
else
    mapfile -t contents < "$CREDFILE"
fi

# Iterate each line in the file, i.e. each credential.
i=0
for cred in "${contents[@]}"; do
    $MOVEMAIL $MOVEMAILFLAGS "$cred" "$DESTFILE"

    ((i+=1))
    echo "mail-fetch: Fetched entry $i."
done
