#!/bin/bash
set -e

# Print one of every N pages. Used for increasing or decreasing the page number.
PAGE_STEP=2

#-------------------------------------------------------------------------------

if [ $# -lt 3 ]; then
    echo "Usage: $(basename "$0") PAGE-START PAGE-END FILE [OPTIONS ...]" 1>&2
    exit 1
fi

if [ ! $(command -v lpr) ]; then
    echo "The 'lpr' command is not installed." 1>&2
    exit 1
fi

#-------------------------------------------------------------------------------

PAGE_START=$1
PAGE_END=$2
FILE=$3
LPR_OPTS=${@:4}

print_page() {
    echo "Sending to queue: $1"
    lpr $LPR_OPTS -o page-ranges=$1 "$FILE"
}

echo "Note: Printing in the specified order ($PAGE_START -> $PAGE_END) with a step of $PAGE_STEP."
if [ $PAGE_START -le $PAGE_END ]; then
    for (( i=$PAGE_START; i<=$PAGE_END; i+=$PAGE_STEP )); do
        print_page $i
    done
else
    for (( i=$PAGE_START; i>=$PAGE_END; i-=$PAGE_STEP )); do
        print_page $i
    done
fi
