#!/usr/bin/env bash
set -e

INTERFACE="enp7s0"

#-------------------------------------------------------------------------------

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be ran as root."
    exit 1
fi

#-------------------------------------------------------------------------------

assert_cmd() {
    if [ ! "$(command -v '$1')" ]; then
        echo "The '$1' command is not installed." 1>&2
        exit 1
    fi
}

assert_cmd "ip"
assert_cmd "macchanger"

#-------------------------------------------------------------------------------

ip a
echo
read -p "Randomizing interface '$INTERFACE'. Press any key to continue..."

echo -n "Bringing interface down... "
ip link set "$INTERFACE" down
echo "Done."

macchanger -a "$INTERFACE"

echo -n "Bringing interface up... "
ip link set "$INTERFACE" up
echo "Done."
