#!/usr/bin/env bash
set -e

if [ $# -lt 1 ]; then
    echo "Usage: $(basename "$0") FILE [OPTION]..." 1>&2
    exit 1
fi

if [ ! $(command -v "source-highlight") ]; then
    echo "The 'source-highlight' command is not installed." 1>&2
    exit 1
fi

source-highlight          \
    --output="STDOUT"     \
    --input="$1"          \
    --out-format="esc256" \
    --failsafe            \
    ${@:2}
