#!/bin/bash
set -e

if [ $# -lt 1 ]; then
    echo "Usage: $0 FILE [OPTIONS ...]" >&2
    exit 1
fi

source-highlight          \
    --output="STDOUT"     \
    --input="$1"          \
    --out-format="esc256" \
    --failsafe            \
    ${@:2}
