#!/bin/bash

RM_OBJ=true           # Remove object file after linking
ASFLAGS="-f elf"      # Assembler
LDFLAGS="-m elf_i386" # Linker

#-------------------------------------------------------------------------------

if [[ ! -f $1 ]]; then
    echo "[nasmo] Error. No such file."
    exit 1;
fi

obj_file="$(echo $1 | cut -d '.' -f 1).o"
out_file="${obj_file}ut"  # *.o -> *.out

if [[ -f $obj_file ]]; then
    rm $obj_file
fi
if [[ -f $out_file ]]; then
    rm $out_file
fi

nasm $ASFLAGS $1

if ! [[ -f $obj_file ]]; then
    echo "[nasmo] Error. Can't find the object file after assembling."
    exit 1;
fi

ld $LDFLAGS -o $out_file $obj_file

if [[ $RM_OBJ == true ]]; then
    rm $obj_file  # Remove object file after linking
fi
