#!/bin/bash

DMENU='dmenu -x 0 -y 0 -z 1920 -fn dina:pixelsize=10 -nb #111111 -nf #777777 -sb #aaaaaa -sf #111111 -i -l 5'
choice=$(echo -e "Root terminal\nPower off\nReboot\nBack to TTY\nExit menu" | $DMENU)

case "$choice" in
	Root\ terminal)
		st -e su -
		;;
	Power\ off)
		poweroff
		;;
	Reboot)
		reboot
		;;
	Back\ to\ TTY)
		pkill dwm
		;;
	Exit\ menu)
		exit 0
		;;
esac
