#!/bin/sh

######################
deviceid="15"
font="dina:size=7"
######################

choice=`cat <<EOF | xmenu

 Normal	0
 Left	1
 Right	2
 Inverted	3
 Exit	4

EOF`

case "$choice" in
	3) xrandr -o 2; xsetwacom set $deviceid Rotate half ;;
	1) xrandr -o 3; xsetwacom set $deviceid Rotate cw ;;
	2) xrandr -o 1; xsetwacom set $deviceid Rotate ccw ;;
	0) xrandr -o 0; xsetwacom set $deviceid Rotate none ;;
	4) exit 0 ;;
esac
