#!/bin/sh

######################
deviceid="15"
font="dina:size=7"
######################

choice=`cat <<EOF | xmenu

	0
	1
	2
	3
 	4

EOF`

case "$choice" in
	3) xrandr -o 2; xsetwacom set $deviceid Rotate half ;;
	1) xrandr -o 3; xsetwacom set $deviceid Rotate cw ;;
	2) xrandr -o 1; xsetwacom set $deviceid Rotate ccw ;;
	0) xrandr -o 0; xsetwacom set $deviceid Rotate none ;;
	4) exit 0 ;;
esac
