#!/bin/bash

###################
multibattery=true
###################

dte(){
        dte="$(date +"%d-%b %R")"
        echo " $dte"
}

hdd(){
        hdd="$(df -h /home | grep dev | awk '{print$5}')"
        echo " $hdd"
}

mem(){
        mem="$(free -h | awk '/Mem:/ {printf $3 "-" $2}')"
        echo " $mem"
}

cpu() {
    read cpu a b c previdle rest < /proc/stat
      prevtotal=$((a+b+c+previdle))
        sleep 0.5
          read cpu a b c idle rest < /proc/stat
            total=$((a+b+c+idle))
              cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
                echo "  $cpu% "
}

pkgs(){
        pkgs="$(apt list --installed | wc -l)"
        echo " $pkgs"
}

vpn(){
        vpn="$(ip a | grep tun0 | grep inet | wc -l)"
        echo " VPN: $vpn"
}

vol(){
	vol="$(amixer -D pulse get Master | awk -F'[][]' 'END{print $2}')"
	muted="$(amixer -D pulse get Master | awk -F'[][]' 'END{print $4}')"
	if [[ $muted == off ]]; then
		echo " Muted"
	else
		echo " $vol"
	fi
}

batt(){
	if [[ $multibattery == false ]]; then
		batt1=$(acpi | awk '{print $4}' | sed s/,//)
		echo " $batt1"
	else
		if [[ $(acpi | head -n 1 | awk '{print $4}' | sed s/,//) == "charging" ]]; then		# If battery is not being charged we use the 5th field
			batt1=$(acpi | head -n 1 | awk '{print $5}' | sed s/,//)
		else
			batt1=$(acpi | head -n 1 | awk '{print $4}' | sed s/,//)
		fi

		if [[ $(acpi | tail -n 1 | awk '{print $4}' | sed s/,//) == "charging" ]]; then
			batt2=$(acpi | tail -n 1 | awk '{print $5}' | sed s/,//)
		else
			batt2=$(acpi | tail -n 1 | awk '{print $4}' | sed s/,//)
		fi

		echo " $batt1 - $batt2"
	fi
}

status(){
	echo "$(cpu) | $(mem) | $(hdd) | $(vol) | $(batt) | $(dte)"

}


while true; do
	xsetroot -name "$(status)"
	sleep 1
done &
