#!/bin/sh
dte(){
        dte="$(date +"%d-%b %R")"
        echo " $dte"
}

hdd(){
        hdd="$(df -h /home | grep dev | awk '{print$5}')"
        echo " $hdd"
}

mem(){
        mem="$(free -h | awk '/Mem:/ {printf $3 "-" $2}')"
        echo " $mem"
}

cpu() {
    read cpu a b c previdle rest < /proc/stat
      prevtotal=$((a+b+c+previdle))
        sleep 0.5
          read cpu a b c idle rest < /proc/stat
            total=$((a+b+c+idle))
              cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
                echo "  $cpu% "
}

pkgs(){
        pkgs="$(apt list --installed | wc -l)"
        echo " $pkgs"
}

vpn(){
        vpn="$(ip a | grep tun0 | grep inet | wc -l)"
        echo " VPN: $vpn"
}

vol(){
	vol="$(amixer -D pulse get Master | awk -F'[][]' 'END{print $4":"$2}')"
	echo " $vol"
}

batt(){
	batt=$(acpi | awk '{print $4}' | sed s/,//)
	echo " $batt"
}

status(){
	#echo "$(cpu) | $(mem) | $(hdd) | $(pkgs) | $(vpn) | $(vol) |  ch0colate's debian - dwm-6.2 | $(dte)"
	#echo "$(cpu) \ $(mem) \ $(hdd) \ $(batt) \  dwm-6.2 \ $(dte)"
	echo "$(cpu) \ $(mem) \ $(hdd) \ $(batt) \ $(dte)"

}


while true; do
	xsetroot -name "$(status)"
	batteryalert.sh  # Will check if the battery is bellow 20%, if so, will display an alert.
	sleep 15
done &
