
# See dotfiles/xbindkeysrc
[[ $(command -v xbindkeys) ]] && xbindkeys

# See dotfiles/xmodmap
[[ -f ~/.xmodmap ]] && xmodmap ~/.xmodmap

# Background
[[ $(command -v xwallpaper) && -f ~/02-Media/01-Images/WALLPAPER.png ]] && xwallpaper --maximize ~/02-Media/01-Images/WALLPAPER.png

# DWM statusbar loop
[[ -f ~/.my-scripts/dwmbar.sh ]] && bash ~/.my-scripts/dwmbar.sh 2>/dev/null

# See scripts/home
[[ -f ~/.my-scripts/change-layout.sh ]] && bash ~/.my-scripts/change-layout.sh

# Saved with arandr
[[ -f ~/.my-scripts/multiple-monitors.sh ]] && bash ~/.my-scripts/multiple-monitors.sh

# You might need to use the following line if using pipewire on gentoo. See
# gentoo's pipewire wiki page.
#     exec dbus-launch --exit-with-session dwm
# Otherwise, just launch normally
exec dwm
