
# See scripts/usr
[[ $(command -v ras) ]] && ras

# See dotfiles/xbindkeysrc
[[ $(command -v xbindkeys) ]] && xbindkeys

# See scripts/home
[[ -f ~/.change-layout.sh ]] && bash ~/.change-layout.sh

# Saved with arandr
[[ -f ~/.screenlayout/main.sh ]] && bash ~/.screenlayout/main.sh

# See dotfiles/xmodmap
[[ -f ~/.xmodmap ]] && xmodmap ~/.xmodmap

# You might need to use the following line if using pipewire on gentoo. See gentoo's 
# pipewire wiki page.
#exec dbus-launch --exit-with-session dwm
exec dwm

